### ISSUE TITLE
How to get it working with OnePlus 3T?

### ISSUE THREAD

**Issue by MrCsabaToth** [Manouchehri/Feitian-MultiPass-FIDO-U2F#1]
https://android.stackexchange.com/questions/186432/how-to-get-feitian-multipass-fido-working-with-oneplus-3t

It pairs up, but when it was about to enter the 6 digit code, the Android app errors out with "Something went wrong". NFC doesn't work either.

**Comment by Manouchehri** [comment]
Are you able to test it on a stock Android 6.0.1 ROM? (Trying to narrow down if it's a hardware or software issue.)

**Comment by MrCsabaToth** [comment]
No, maybe this weekend. Maybe first I'll just try an unrooted Oxygen ROM.

**Comment by Manouchehri** [comment]
I've had some BLE issues on 7.x, not sure if it's due to the root or new permissions.

**Comment by MrCsabaToth** [comment]
Solved it. It was the rooting + custom bootloader. I switch from SuperSU + SU hide (the latter never worked 100%) to Magisk. Latest beta Magisk was good enough to trick SafetyNet and now I even have Android Pay besides being able to use the Feitian through BLE.
